### ISSUE TITLE
Why does code snippets overwrite the next line?

### ISSUE THREAD

**Issue by SimonCropp** [shiftkey/scribble#21]
In this test https://github.com/shiftkey/scribble/tree/master/src/Scribble.CodeSnippets/Scribble.CodeSnippets.Tests/scenarios/3-UpdateSimpleFileOverwritesNextLine

why should this

```
< !-- import my-code-snippet -->
this is a message which should be deleted
```

output this

```
< !-- import my-code-snippet -->
    this is some text to import
```

ie why would you overwrite the next line?

**Comment by shiftkey** [comment]
If there is any text immediately below the placeholder, it should get replaced by the code snippet.

Say, for example, the placeholder key changes, but the content below does not.

This is just a test to illustrate that behaviour.

**Comment by SimonCropp** [comment]
> If there is any text immediately below the placeholder, it should get replaced by the code snippe

OK but what let you to decide that this was the correct behaviour? 

I would have assumed you would only replace indented text if it was below the placeholder? Non indented text I would have just bumped down.

Not suggesting it be changed. just want to understand the requirement

**Comment by shiftkey** [comment]
For me at least, indented text is just a code snippet, so it should be treated like an old code snippet

**Comment by SimonCropp** [comment]
Yep. Agreed on overwriting the indented text. Not so sure about overwriting non indented. 

Also for non indented what are the rules? Do you overwrite till the next empty line? Just overwrite one line? Overwrite the same number of lines as the code snippet?

**Comment by shiftkey** [comment]
Ok, so there's an Unwritten Rule here that all code snippets are indented four characters (so Markdown renders it as code).

And one other rule is "insert an empty line after the code snippet.

So for a scenario where it's like this

```
<!-- start code foo -->
i am just a sentence

```

What's the expected output? 

This?

```
<!-- start code foo -->
   public class CodeSnippet { }  

i am just a sentence

```

or 

```
<!-- start code foo -->
   public class CodeSnippet { }  

```

Which makes more sense?

**Comment by SimonCropp** [comment]
ok so based on our conversation 

I will go with this 

```
<!-- start code foo -->
   public class CodeSnippet { }  

i am just a sentence
```
