### ISSUE TITLE
Ship codesnippets as a stand alone nuget

### ISSUE THREAD

**Issue by SimonCropp** [shiftkey/scribble#22]

**Comment by shiftkey** [comment]
Just the binary or did you have a specific API surface in mind?

**Comment by SimonCropp** [comment]
i had to make one change to the API to make it usable from MarkPad. Which i will do a PR for

The rest has been perf improvements. When i am finished on my fork we can have a conversation about the changes

**Comment by shiftkey** [comment]
Me:

![](http://i.imgur.com/erErsLz.gif)
