### ISSUE TITLE
Did not create folders / documentation in VS2012

### ISSUE THREAD

**Issue by derekmurawsky** [shiftkey/scribble#5]
I ran Install-Package scribble -Pre in my existing project, and no additional folders were created, nor was the browser opened. I am running VS2012. Could this be a version issue?

**Comment by shiftkey** [comment]
What version?

**Comment by derekmurawsky** [comment]
scribble 0.4.1.2-pre
I just did it again now to confirm on a separate WCF project in VS2012 Premium, 11.0.60204.01 Update 2 CTP

**Comment by shiftkey** [comment]
Same thing happening here - guess I broke something recently.

I'll crank up the diagnostics and push out another package this evening and see what's changed.

**Comment by derekmurawsky** [comment]
Ok. Please let me know if I can assist with anything.

**Comment by shiftkey** [comment]
Turns out I forgot a parameter in the TeamCity config and it was generating an incorrect package.

I've published up  `0.4.1.4-pre` which I tested, and it's back to normal.

Thanks for spotting the problem in the first place!
