### ISSUE TITLE
Still have issues in VS2012

### ISSUE THREAD

**Issue by derekmurawsky** [shiftkey/scribble#7]
This is a continuation of #5 
Still having issues in VS2012 Premium. 
Install-Package scribble -Pre

Command prompt comes up now and errors out in Pretzel. It looks like a quotes error on the directory name. 
Unhandled exception: System.IO.DirectoryNotFoundException: Could not find part of the path 'C:\users\dmurawsky.POLARIS\documents\visual'

![2013-03-27 10_00_28-BulkMailer - Microsoft Visual Studio Administrator ](https://f.cloud.github.com/assets/3741839/308391/bcc166d2-96e6-11e2-863c-f51a89c0d7a3.png)

**Comment by shiftkey** [comment]
Sweet, folders with spaces in them. Should be easy to find and fix.

**Comment by shiftkey** [comment]
Fixed in `0.4.1.6`
